name: Update README Moon Phase

on:
  schedule:
    - cron: "0 */6 * * *"  # Every 6 hours
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pytz

      - name: Run update script
        run: python update_moon_phase.py

      - name: Commit and push changes
        run: |
          git config --global user.name "mayank-hassija"
          git config --global user.email "mayankhassija@gmail.com"
          git add README.md
          git diff --cached --quiet || git commit -m "🌙 Update README moon phase"
          git push
